version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      USER_NAME: "Your Name"
      USER_URL: "https://yourwebsite.com"
    secrets:
      - db_url
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      bash -c "flask db upgrade && flask run"

secrets:
  db_url:
    external: true



