version: '3.1'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://admin:securepassword@app_db:5432/app_db"
      USER_NAME: "Your Name"
      USER_URL: "https://yourwebsite.com"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    command: >
      bash -c "flask db upgrade && flask run"
    depends_on:
      - app_db

  app_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
